// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ShakeOnDamage","status":true,"description":"受伤时的震动插件","parameters":{"シェイク強さ":"5","クリティカルシェイク強さ":"9","弱点シェイク強さ":"9","シェイク速さ":"9","シェイク時間":"30","アクターに適用":"true","敵キャラに適用":"false"}},
{"name":"(MZ)hsyq16对战斗敌人窗口添加血条","status":true,"description":"","parameters":{}},
{"name":"BattleResultsPopup","status":true,"description":"用一个战斗结果结算窗口来替代系统默认的文本战斗结果显示。","parameters":{}},
{"name":"AutoRaise","status":true,"description":"自动复活插件","parameters":{"蘇生アニメID":"49","蘇生アイコンID":"72"}}
];
